//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGSC
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sgscEntities : DbContext
    {
        public sgscEntities()
            : base("name=sgscEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BankAccounts> BankAccounts { get; set; }
        public virtual DbSet<Banks> Banks { get; set; }
        public virtual DbSet<Colonies> Colonies { get; set; }
        public virtual DbSet<Contacts> Contacts { get; set; }
        public virtual DbSet<CreditConditions> CreditConditions { get; set; }
        public virtual DbSet<CreditPolicies> CreditPolicies { get; set; }
        public virtual DbSet<CreditPromotions> CreditPromotions { get; set; }
        public virtual DbSet<CreditRequestCreditPolicies> CreditRequestCreditPolicies { get; set; }
        public virtual DbSet<CreditRequests> CreditRequests { get; set; }
        public virtual DbSet<CustomerAddresses> CustomerAddresses { get; set; }
        public virtual DbSet<CustomerContactInfoes> CustomerContactInfoes { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Documents> Documents { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Payments> Payments { get; set; }
        public virtual DbSet<WorkCenters> WorkCenters { get; set; }
    }
}
